"""The public API is frozen (§Stability in docs/en/api.md).

`reactifact.__all__` and each core submodule's `__all__` are the stable
contract: every name here is documented and covered by SemVer. This test pins
the exact set, so a new export has to be added deliberately (and to the docs)
rather than slipping out by accident. If it fails, either remove the export or
extend `FROZEN` and document the symbol.
"""

from __future__ import annotations

import importlib

import pytest

FROZEN: dict[str, frozenset[str]] = {
    "reactifact": frozenset(
        {
            "Agent",
            "Artifact",
            "Budget",
            "BudgetTracker",
            "Consume",
            "Context",
            "Create",
            "Delete",
            "Effects",
            "EmbeddingProvider",
            "Event",
            "EventType",
            "FakeEmbedder",
            "FakeLLM",
            "FunctionTool",
            "Handle",
            "LLMProvider",
            "LLMRequest",
            "LLMResponse",
            "LLMResponseChunk",
            "Link",
            "MergeConflict",
            "Message",
            "Patch",
            "PendingQuestion",
            "Produce",
            "ProduceCall",
            "Relation",
            "ResourceKey",
            "ResourceScope",
            "RunOutcome",
            "RunStats",
            "Runtime",
            "RuntimeResources",
            "Session",
            "SessionStore",
            "Tool",
            "ToolOutput",
            "Trigger",
            "Unlink",
            "Update",
            "View",
            "consume",
            "create_agent",
            "current_request",
            "produce",
            "register_type",
            "tool",
        }
    ),
    "reactifact.eval": frozenset(
        {
            "CORRECTNESS_INSTRUCTIONS",
            "Dataset",
            "EvalCase",
            "EvalFailure",
            "EvalInput",
            "EvalReport",
            "EvalResult",
            "Evaluator",
            "EvaluatorResult",
            "Example",
            "Extractor",
            "FAITHFULNESS_INSTRUCTIONS",
            "Feedback",
            "FeedbackLike",
            "JUDGE_SYSTEM",
            "JudgeParser",
            "Metric",
            "MetricFn",
            "OnlineEvalConfig",
            "OnlineEvaluator",
            "OnlineReport",
            "RELEVANCE_INSTRUCTIONS",
            "RunFn",
            "RunResult",
            "StepExtractor",
            "SummaryEvaluator",
            "Target",
            "TraceSource",
            "TrajectoryMode",
            "aevaluate",
            "answer_coverage",
            "answer_present",
            "assert_eval",
            "calculation_correctness",
            "claim_verification",
            "confidence_calibration",
            "context_source",
            "core_metrics",
            "create_online_eval_router",
            "default_outputs",
            "evaluate",
            "evidence_quality",
            "from_metric",
            "judge_correctness",
            "judge_faithfulness",
            "judge_relevance",
            "llm_judge",
            "no_errors",
            "online_evaluate",
            "output_present",
            "parse_judgement",
            "provenance_grounded",
            "run_case",
            "run_suite",
            "source_coverage",
            "summary_mean",
            "summary_pass_rate",
            "trace_source",
            "trajectory_match",
        }
    ),
    "reactifact.recipes": frozenset(
        {
            "ApprovalGate",
            "Conversation",
            "ConversationMessage",
            "EN_STOPWORDS",
            "EphemeralCleanup",
            "MessageSpec",
            "PlanExecute",
            "PrefixedEphemeralCleanup",
            "ReflectionLoop",
            "RollingDigestSummarizer",
            "Router",
            "SeedIdentity",
            "Skill",
            "StatusMachine",
            "ToolLoopResult",
            "ToolObservation",
            "Transcript",
            "WindowPruner",
            "WindowSummarizer",
            "add_message",
            "changed_fields",
            "conversation_state",
            "create_turn",
            "downstream_fields",
            "earliest_stage",
            "fan_out_sources",
            "find",
            "find_all",
            "keyword_score",
            "llm_digest_summarizer",
            "llm_summarizer",
            "load_skills",
            "match_skills",
            "materialize_doc",
            "run_tool_loop",
            "stem",
            "stem_words",
            "transcript",
            "turn_count",
        }
    ),
    "reactifact.providers": frozenset(
        {
            "AnthropicProvider",
            "EmbeddingProvider",
            "FakeEmbedder",
            "FakeLLM",
            "GeminiImageProvider",
            "GeminiProvider",
            "ImageProvider",
            "LLMProvider",
            "LLMRequest",
            "LLMResponse",
            "LLMResponseChunk",
            "LumaVideoProvider",
            "Message",
            "OpenAICompatEmbedder",
            "OpenAICompatImageProvider",
            "OpenAICompatProvider",
            "OpenAICompatSpeech",
            "OpenAICompatTranscriber",
            "OpenRouterImageProvider",
            "OpenRouterVideoProvider",
            "Role",
            "RunwayVideoProvider",
            "SoraVideoProvider",
            "SpeechProvider",
            "TranscriberProvider",
            "VideoProvider",
            "VideoResult",
            "anthropic_llm",
            "azure_llm",
            "cerebras_llm",
            "deepseek_llm",
            "embedder_from_env",
            "fireworks_embedder",
            "fireworks_llm",
            "from_env",
            "gemini_image",
            "gemini_llm",
            "github_models_llm",
            "groq_llm",
            "groq_transcriber",
            "image_from_env",
            "llm_from_env",
            "mistral_embedder",
            "mistral_llm",
            "nvidia_embedder",
            "nvidia_nim_llm",
            "ollama_llm",
            "openai_embedder",
            "openai_llm",
            "openrouter_embedder",
            "openrouter_image",
            "openrouter_llm",
            "openrouter_speech",
            "perplexity_llm",
            "qwen_embedder",
            "qwen_llm",
            "speech_from_env",
            "together_embedder",
            "together_llm",
            "transcriber_from_env",
            "video_from_env",
            "xai_llm",
            "zai_llm",
        }
    ),
    "reactifact.tracing": frozenset(
        {
            "AgentSpan",
            "ArtifactRef",
            "CompositeTracer",
            "LLMCall",
            "LangfuseTracer",
            "OTLPTracer",
            "PostgresStore",
            "RecordingLLM",
            "RelationRef",
            "RunTrace",
            "RunTracer",
            "Tag",
            "TagAssignment",
            "TraceAnnotator",
            "TraceColumn",
            "TraceReader",
            "TraceSink",
            "TraceStore",
            "TraceStoreProtocol",
            "Tracer",
        }
    ),
}


@pytest.mark.parametrize("module_name", sorted(FROZEN))
def test_public_all_is_frozen(module_name: str) -> None:
    module = importlib.import_module(module_name)
    assert frozenset(module.__all__) == FROZEN[module_name], (
        f"{module_name}.__all__ changed; update FROZEN and the docs"
    )


@pytest.mark.parametrize("module_name", sorted(FROZEN))
def test_every_export_exists(module_name: str) -> None:
    module = importlib.import_module(module_name)
    missing = [name for name in module.__all__ if not hasattr(module, name)]
    assert not missing, f"{module_name}.__all__ lists missing names: {missing}"
